class UserNotFoundException(Exception):
    pass


class CompanyNotFoundException(Exception):
    pass
